export const appText = {
    titleApp: 'Bogarts'
    , titleWelcome: '¡Bienvenido!'
    , titleLogIn: 'Iniciar sesión'
    , titleSignUp: 'Registrarse'
    , titleReset: 'Recuperar contraseña'
    , titleDetail: 'Detalle'
    , titleCreate: 'Nuevo'
    , titleEdit: 'Edición'
    , titleDelete: 'Eliminar registro'
    , titleToggleStatus: 'Cambiar estatus'
    , titleMenu: 'Menú principal'
    , title404Page: 'Lo sentimos, la página que desea visitar no existe.'
    , titleHome: 'Inicio'
    , titleFunctions: 'Funciones básicas'
    , titleSpecialFunctions: 'Funciones especiales'
    , titleMyProfile: 'Mi perfil'

    , questionConfirmDelete: '<span class="d-block text-left mb-3">¿Está seguro de que desea eliminar el registro?</span><span class="d-block small text-right font-italic text-muted">Esta acción es irreversible.</span>'
    , questionConfirmToggleStatus: '¿Está seguro de que desea cambiar el estatus del registro?'
    , registers: 'Registros'
    , forgotPassword: '¿Olvidó su contraseña?'
    , yes: 'Si'
    , no: 'No'
    , close: 'Cerrar'
    , delete: 'Eliminar'
    , status: 'Estatus'
    , statusAll: 'Todos'
    , statusEnable: 'Activo'
    , statusDisable: 'Inactivo'
    , statusPending: 'Pendiente'
    , loading: 'Cargando...'
    , defaultOption: 'Seleccione'
    , withoutNotifications: 'Sin notificaciones'
    , unknow: 'Desconocido'
    , information: 'Información'
    , placeholderSearch: 'Buscar...'
    , emptyTable: 'Sin registros'
    , lastLogInDate: 'Última sesión: '
    , cancelCreation: 'Se perderan todos los datos capturados.'
    , cancelEdition: 'Se perderan todos los datos modificados.'

    , btnLogIn: 'Iniciar sesión'
    , btnReset: 'Restablecer contraseña'
    , btnSingUp: 'Registrarme'
    , btnLogOut: 'Cerrar sesión'
    , btnBack: 'Regresar'
    , btnCreate: 'Nuevo'
    , btnExport: 'Exportar'
    , btnImport: 'Carga masiva'
    , btnSave: 'Guardar'
    , btnCancel: 'Cancelar'
    , btnSearch: 'Buscar'
    , btnMyProfile: 'Mi perfil'
    , btnUnblockUser: 'Desbloquear usuario'
    , btnToday: 'Hoy'

    , lbName: 'Nombre'
    , lbLastName: 'Apellido(s)'
    , lbEmail: 'Correo electrónico'
    , lbUser: 'Usuario'
    , lbPassword: 'Contraseña'
    , lbConfirmPassword: 'Confirmar contraseña'
    , lbKeyname: 'Alias de la empresa'
    , lbLevel: 'Nivel'
    , lbDescription: 'Descripción'
    , lbCreationDate: 'Fecha de creación'
    , lbEditionDate: 'Fecha de modificación'
    , lbStatus: 'Estatus'
    , lbPhone: 'Teléfono'
    , lbIsBlocked: '¿Bloqueado?'
    , lbIsConnected: '¿Conectado?'
    , lbAddress: 'Dirección'
    , lbProfile: 'Perfil'
    , lbPosition: 'Puesto'
    , lbStreet: 'Calle'
    , lbOutNumber: 'Num. Ext.'
    , lbInNumber: 'Num. Int.'
    , lbZipCode: 'Código Postal'
    , lbCountry: 'País'
    , lbState: 'Estado'
    , lbLocality: 'Alcaldia o Municipio'
    , lbColony: 'Colonia'
    , lbOpeningTime: 'Hora de apertura'
    , lbClosingTime: 'Hora de cierre'

    , columnName: 'Nombre'
    , columnValue: 'Valor'
    , columnDescription: 'Descripción'
    , columnActions: 'Acciones'
    , columnScreen: 'Pantalla'
    , columnQuery: 'Consulta'
    , columnDetail: 'Detalle'
    , columnCreate: 'Crear'
    , columnEdit: 'Editar'
    , columnDelete: 'Eliminar'
    , columnToggleStatus: 'C. Estatus'
    , columnExport: 'Exportar'
    , columnFunction: 'Funcion'

    , msjUserRequired: 'El usuario es requerido.'
    , msjPasswordRequired: 'La contraseña es requerida.'
    , msjPasswordDiferent: 'La contraseña no coincide.'
    , msjEmailRequired: 'El correo electrónico es requerido.'
    , msjNameRequired: 'El nombre es requerido.'
    , msjLastNameRequired: 'El apellido(s) es requerido.'
    , msjEnterpriseRequired: 'El alias de la empresa es requerido.'
    , msjLevelRequired: 'El nivel es requerido'
    , msjLevelInvalid: 'El nivel debe ser mayor o igual a 1'
    , msjPhoneRequired: 'El número de teléfono es requerido'
    , msjProfileRequired: 'El perfil es requerido'
    , msjPositionRequired: 'El puesto es requerido'
    , msjStreetRequired: 'La calle es requerida'
    , msjOutNumberRequired: 'El número exterior es requerido'
    , msjZipCodeRequired: 'El código postal es requerido'
    , msjZipCodeLength: 'El código postal debe ser de 5 digitos'
    , msjDescriptionRequired: 'La descripción es requerida'
    , msjOpeningTimeRequired: 'La hora de apertura es requerida'
    , msjClosingTimeRequired: 'La hora de cierrre es requerida'

    , requestErrorTimeSession: 'Lo sentimos, por seguridad su sesión ha expirado.'
    , requestErrorUnknow: 'Error desconocido.'

    , answerException: 'Ha ocurrido un error.'
    , answerCorrect: 'Proceso completado correctamente.'
    , answerCorrectLogIn: '¡Bienvenido!'
    , answerCorrectResetPassword: 'Tu contraseña ha sido restablecida correctamente.'
    , answerCorrectChangePassword: 'Tu contraseña ha sido actualizada correctamente.'
    , answerCorrectUnblock: 'El usuario ha sido desbloqueado correctamene.'
    , answerCorrectCreating: 'El registro ha sido creado correctamente.'
    , answerCorrectEdition: 'El registro ha sido actualizado correctamente.'
    , answerCorrectDeleting: 'El registro ha sido eliminado correctamente.'
    , answerCorrectToggleStatus: 'El estatus del registro ha sido actualizado correctamente'
    , answerCorrectExport: 'La descarga de la información ha sido completada correctamente.'
    , answerEmpty: 'No ha sido posible encontrar información con los filtros establecidos.'
    , answerIncorrect: 'Lo sentimos! Ha ocurrido un problema.'
    , answerIncorrectToken: 'El token es inválido.'
    , answerIncorrectCreating: 'No ha sido posible crear el registro.'
    , answerIncorrectEdition: 'No ha sido posible actualizar el registro.'
    , answerIncorrectDeleting: 'No ha sido posible eliminar el registro.'
    , answerIncorrectToggleStatus: 'No ha sido posible cambiar el estatus el registro.'
    , answerIncorrectExport: 'No ha sido posible descargar la información.'
    , answerIncorrectCredentials: 'Los datos de acceso son incorrectos.'
    , answerUserUnregistered: 'El usuario capturado no existe en el sistema.'
    , answerUserBlocked: 'Su usuario se encuentra bloqueado. Contacte a su administrador.'
    , answerUserConnected: 'Se encuentra con una sesión activa en estos momentos. Contacte a su administrador.'
    , answerUserOverAttempts: 'Su usuario ha sido bloqueado. Contacte a su administrador.'
    , answerFunctionNotAllowed: 'No tiene permisos para ejecutar la acción solicitada.'
    , answerRecordDoesNotExist: 'No ha sido posible encontrar el registro.'
    , answerRecordUsed: 'El registro se encuentra utilizado en estos momentos.'
};

